server:
  port: 8080

spring:
  application:
    name: apiGateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: department_service
          uri: http://localhost:8002
          predicates:
            - Path=/department_service/**
          filters:
            - StripPrefix=1

        - id: employee_service
          uri: http://localhost:8001
          predicates:
            - Path=/employee_service/**
          filters:
            - StripPrefix=1

        - id: course-service
          uri: http://localhost:8005
          predicates:
            - Path=/course-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


